ss_cse:
  build: ./cse
  ports:
    - "3000"
  env_file: ./cse/.env

ss_nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  links:
    - ss_cse:ss_cse
    - ss_elastic:ss_elastic

ss_elastic:
  image: elasticsearch:2.3
  ports:
    - "9300:9000"

ss_data:
  build: ./data
  volumes:
    - /data

ss_indexer:
  build: ./indexer
  links:
    - ss_elastic:ss_elastic
  volumes_from:
    - ss_data
