ss_cse:
  build: ./cse
  ports:
    - "3000"
  env_file: ./cse/.env

ss_nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  links:
    - ss_cse:ss_cse

ss_elastic:
  image: elasticsearch:2.3
  volumes_from:
    - ss_data

ss_data:
  build: ./data
  volumes:
    - /data
